// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWC-TWTSdPQOzTpMNJmKdhJYTpbk2hQpo',
    appId: '1:3351451919:web:8a4796dc322838b873c67a',
    messagingSenderId: '3351451919',
    projectId: 'roteopt',
    authDomain: 'roteopt.firebaseapp.com',
    storageBucket: 'roteopt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOLTr2Gv_v4q_0e42cri2KRoEAYO8tQo',
    appId: '1:3351451919:android:8d9237da9db367b973c67a',
    messagingSenderId: '3351451919',
    projectId: 'roteopt',
    storageBucket: 'roteopt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbMaf4pqpJOOwjHo0u1PZaW-DGqxNShg',
    appId: '1:3351451919:ios:4751922cbf63db1e73c67a',
    messagingSenderId: '3351451919',
    projectId: 'roteopt',
    storageBucket: 'roteopt.firebasestorage.app',
    iosBundleId: 'com.example.rotaotimizada',
  );
}
